package main

var characters []Character = []Character{
	{Name: "Mario", Weight: "Medium-Heavy"},
	{Name: "Luigi", Weight: "Medium-Heavy"},
	{Name: "Peach", Weight: "Medium"},
	{Name: "Daisy", Weight: "Medium"},
	{Name: "Yoshi", Weight: "Medium"},
	{Name: "Toad", Weight: "Light"},
	{Name: "Koopa Troopa", Weight: "Light"},
	{Name: "Shy Guy", Weight: "Light"},
	{Name: "Bowser", Weight: "Heavy"},
	{Name: "Donkey Kong", Weight: "Heavy"},
	{Name: "Wario", Weight: "Heavy"},
	{Name: "Waluigi", Weight: "Medium-Heavy"},
	{Name: "Rosalina", Weight: "Heavy"},
	{Name: "Metal Mario", Weight: "Heavy"},
	{Name: "Pink Gold Peach", Weight: "Heavy"},
	{Name: "Lakitu", Weight: "Light"},
	{Name: "Toadette", Weight: "Light"},
	{Name: "Baby Mario", Weight: "Very Light"},
	{Name: "Baby Luigi", Weight: "Very Light"},
	{Name: "Baby Peach", Weight: "Very Light"},
	{Name: "Baby Daisy", Weight: "Very Light"},
	{Name: "Baby Rosalina", Weight: "Very Light"},
	{Name: "Larry", Weight: "Light"},
	{Name: "Morton", Weight: "Heavy"},
	{Name: "Wendy", Weight: "Light"},
	{Name: "Iggy", Weight: "Medium"},
	{Name: "Roy", Weight: "Heavy"},
	{Name: "Lemmy", Weight: "Very Light"},
	{Name: "Ludwig", Weight: "Medium"},
	{Name: "Bowser Jr.", Weight: "Medium-Light"},
	{Name: "Link", Weight: "Medium-Heavy"},
	{Name: "Villager (Male)", Weight: "Medium"},
	{Name: "Villager (Female)", Weight: "Medium"},
	{Name: "Isabelle", Weight: "Light"},
	{Name: "Tanooki Mario", Weight: "Medium"},
	{Name: "Cat Peach", Weight: "Medium"},
	{Name: "Dry Bones", Weight: "Light"},
	{Name: "King Boo", Weight: "Heavy"},
	{Name: "Inkling Boy", Weight: "Medium"},
	{Name: "Inkling Girl", Weight: "Medium"},
	{Name: "Birdo", Weight: "Medium"},
	{Name: "Petey Piranha", Weight: "Heavy"},
	{Name: "Gold Mario", Weight: "Heavy"},
	{Name: "Tanooki Mario", Weight: "Medium"},
	{Name: "Cat Peach", Weight: "Medium"},
}

func SeedCharacter() {
	DB.Create(&characters)
}
